# Site settings
title: finamore.io
description: A blog about lorem ipsum dolor sit amet
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.finamore.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: ALESSANDRO FINAMORE
user_description: --- AAAA --- 
user_title: Developing better networks with BigData and ML
email: finale80@gmail.com
twitter_username: finale80
github_username:  finale80
#gplus_username:  lorem_ipsum
#disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
#  - title: Home
#    url: /
#  - title: Series
#    url: /series
#  - title: Tags
#    url: /tags
#  - title: About Me
#    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
